# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_WILC1000) += wilc1000.o

wilc1000-objs := \
	cfg80211.o \
	hif.o \
	mon.o \
	netdev.o \
	wlan.o \
	wlan_cfg.o


obj-$(CONFIG_WILC1000_SDIO) += wilc1000-sdio.o
wilc1000-sdio-objs += sdio.o

obj-$(CONFIG_WILC1000_SPI) += wilc1000-spi.o
wilc1000-spi-objs += spi.o
