name: Snyc

on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  sync_repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master

      - name: Sync Repo
        uses: tedd-an/bzcafe@dev
        with:
          task: sync
          upstream_repo: "https://git.kernel.org/pub/scm/linux/kernel/git/bluetooth/bluetooth-next.git"
          github_token: ${{ secrets.GITHUB_TOKEN }}

  sync_patchwork:
    needs: sync_repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Sync Patchwork
        uses: tedd-an/bzcafe@dev
        with:
          task: patchwork
          space: kernel
          github_token: ${{ secrets.ACTION_TOKEN }}
          email_token: ${{ secrets.EMAIL_TOKEN }}
          patchwork_token: ${{ secrets.PATCHWORK_TOKEN }}
          patchwork_user: ${{ secrets.PATCHWORK_USER }}
